Coordinate
UdL-EPS-SoftArch/myroutes-api pull request #10
Opened 2023-09-26 16:42 UTC by gmonso

2023-09-26 17:58 UTC, rogargon requested changes

2023-09-26 17:58 UTC, rogargon commented on src/main/java/cat/udl/eps/softarch/myroutes/domain/Coordinate.java
> +public class Coordinate extends UriEntity<String> {
The id is Long, so it should extend UriEntity<Long>

2023-09-26 17:58 UTC, rogargon commented on src/main/java/cat/udl/eps/softarch/myroutes/domain/Coordinate.java
> +        return null;
No need to override getId(), remove the code as it is already generated by Lombok and using the appropriate return type, which is Long and not String.

2023-10-03 13:34 UTC, gmonso commented on src/main/java/cat/udl/eps/softarch/myroutes/domain/Coordinate.java
> +public class Coordinate extends UriEntity<String> {
Fixed, now UriEntity is Long

2023-10-03 13:39 UTC, gmonso commented on src/main/java/cat/udl/eps/softarch/myroutes/domain/Coordinate.java
> +        return null;
Fixed, my ide imports a wrong library and generates this function.

2023-10-04 13:17 UTC, rogargon approved these changes

2023-10-04 13:17 UTC, merged